local Knit = require(game:GetService("ReplicatedStorage").Packages.Knit)

function start()
	local DataService = Knit.GetService("DataService")
	local StateController = Knit.GetController("StateController")
	DataService.UpdateCoins:Connect(function(coins)
		StateController:UpdateCoins(coins)
	end)
	DataService.UpdateStars:Connect(function(stars)
		StateController:UpdateStars(stars)
	end)
	DataService.UpdateFishes:Connect(function(fishes: table)
		StateController:UpdateFishes(fishes)
	end)
	DataService.UpdateExp:Connect(function(exp)
		StateController:UpdateExp(exp)
	end)
	DataService.LevelUp:Connect(function(level)
		StateController:UpdateLevel(level)
	end)
	DataService.ResetData:Connect(function(data)
		StateController:ResetData(data)
	end)
end

Knit:OnStart():andThen(start)
